/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: d15af2067891bb59456fb01fbc8dfdbf)
interface __BaseEnv_CloudflareEnv {
	MEDIA: R2Bucket;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	WORKER_SELF_REFERENCE: Fetcher /* dance-hub-v2-scaffold */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
